### ISSUE TITLE
Configuration Management

### ISSUE THREAD

**Issue by drusellers** [weavejester/duct#27]
When i fire up just a basic duct template for an app named `bob` I get the following:

```
.
├── README.md
├── dev
│   ├── local.clj
│   └── user.clj
├── profiles.clj
├── project.clj
├── src
│   └── bob
│       ├── component
│       ├── config.clj
│       ├── endpoint
│       ├── main.clj
│       └── system.clj
└── test
    └── bob
```

My question centers around how to best manage the configuration state of the application. From the README we see that **"Duct separates configuration and environment."** and we can indeed if we look at the files `config.clj`,

#### config.clj

Contains `bob.config/defaults` (with `meta-merge` `displace` metadata) as well as containing `bob.config/environ` to pull in all keys that we are going to source from the environment. Sweet, i like this a lot.

#### main.clj

Contains the `bob.main/prod-config` which is supposed to contain the production configuration. It also contains the `bob.main/config` definition which is passed into the `new-system` function. To this is not really "production" but a way to separate configuration values from those that we might want to use in the REPL.

#### dev/local.clj

I'll be honest, I'm not sure what goes in here.

#### dev/user.clj 

Contains the `user/dev-config` which is a mirror of the `bob.main/prod-config` and again provides a way of differentiating config values between `lein run` and `lein repl`. There is also the `user/config` which merges the config values in the same way that `bob.main/config` does. I like this symmetry. 

#### project.clj

Finally we have the values in the project themselves. Specifically is the `:project/dev :env :port 3000` setting.

---

Ok, now that we have this all out in the open we can finally get to my main issue which is, "If duct is meant to be a template for web applications with a focus on simplicity, why are there so many places to watch, maintain and monitor for configuration values?"

> Simple: Easy to understand. Composed of one part.

And I know that we aren't trying to just make things one part, we need to separate out the pieces that move. The video linked in the opening of the project README is one of my favorite. So, I think what I'd like to see is duct provide a little bit of guidance on how we should use the various config points that it provides. I say this because i see value in what is being laid out, and now having written this issue I have a much better understanding of what is going on (except for the `local.clj`).

I'd like to suggest that we drop any configuration in the `project.clj` (specifically [this](https://github.com/weavejester/duct/blob/master/lein-template/resources/leiningen/new/duct/base/project.clj#L63)) in favor of putting values in the `bob.config.clj` namespace. To be this makes more sense, rather than trying to much with environment variables in the `project.clj`.

I also think that some of my confusion comes from the way `meta-merge` works in that I want to set some keys in a hash from defaults and then override them in the environment variables but it seems that `meta-merge` ends up [throwing away some keys that I'm not expecting](https://github.com/weavejester/meta-merge/issues/5).

So, all of that said thank you for taking the time to read this very long issue and I look forward to any understanding that you can pass along. I will to the best that I can provide any feedback you give as a pull request to the documentation clarifying any part of this that i have screwed up. :)

**Comment by weavejester** [comment]
Thanks for the suggestions. Let me see if I can cover all of the points you've raised...

[Environ](https://github.com/weavejester/environ) has support for pulling data out of the `:env` key in the project file, which is why the port is specified there. However, I think you're right that it doesn't necessarily make sense in this particular case, since it just echos the default port.

The `:env` key is more useful when used in conjunction with the `profiles.clj` file, which is kept out of source control and allows for local configuration. For instance, you could have a profiles file like:

```clojure
{:dev {:env {:database-url "jdbc:postgresql://localhost/mypostgres"}}}
```

Different developers could setup their development databases with different names and credentials, without affecting anything in source control.

The `dev/local.clj` file is similar, but instead of setting up local profiles, you can run local code when setting up a development environment. For instance, perhaps you want to add a file watch that calls `(reset)` automatically whenever a source file changes, but another developer in your team prefers to bind `(reset)` to a key in Emacs. The `dev/local.clj` file allows different developers to customise their setup.

The environ configuration should probably filter out `nil` values in some way. I'll need to consider the best way to do this.

I'll also add in a wiki page that talks more about the different files and their purpose.

**Comment by drusellers** [comment]
@weavejester so if I understand this correctly, `user.clj` isn't really for a user to customize, an individual developer should customize `local.clj` for anything they may want and `user.clj` is really more for the "team" working on the project. Does that sound right?

**Comment by weavejester** [comment]
That's right.

The `user` namespace is used because it's the default namespace of the Clojure REPL, and the one used in the original [Reloaded Workflow](http://thinkrelevance.com/blog/2013/06/04/clojure-workflow-reloaded) blog post.

The `local` namespace was added after, and is so called because it's designed to be local, outside of version control, and used for individual code that the developer doesn't want to share with the team.

I've been considering changing this to be in line with the latest [reloaded template](https://github.com/stuartsierra/reloaded/blob/master/src/leiningen/new/reloaded/templates/user.clj), where the `user` namespace just has a function in it that loads the `dev` namespace (and the `local` namespace as well, for Duct).

**Comment by drusellers** [comment]
:+1: thank you for responding. I like it and I feel much better informed about everything that is going on. :)
